# Generated by Django 5.0.5 on 2024-05-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('identificacion', models.CharField(max_length=50, unique=True, verbose_name='Identificación')),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
    ]
