# Generated by Django 5.0.5 on 2024-05-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='contrasena',
            field=models.CharField(default='', max_length=128),
        ),
    ]
